apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-v35p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-v35p
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-v35p
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-v35p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-v35p
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lknl-tenant/rhtap-demo-app/hacbs-test-project-v35p@sha256:b1fcc11b308ba2b5ff9b1d46983adcf1c1745bd79eb9947f6fe0f6fe1ba16eaf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
