apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-v35p
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lknl-tenant/rhtap-demo-app/hacbs-test-project-v35p@sha256:343782f516a6bfac1e8b966e2bfc3535fa09dcc71887465809dadb698f2f2165
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
